### ISSUE TITLE
Add the execution time in the output file

### ISSUE THREAD

**Issue by Yoy017** [Yoy017/todo-manager#26]
We have to write the time that a command take to execute at the end of the output file.

**Comment by CamilleThHEIG** [comment]
Know how to do this, if needed

**Comment by Yoy017** [comment]
All good, it's already working !

**Comment by Yoy017** [comment]
Finally, the execution time is working well when all file is overwritten. But I have problem with writting the execution time when we write one task only.

**Comment by Yoy017** [comment]
We should display the execution time on the console. There is no need to write it in the output file (as the teacher answered us).
