### ISSUE TITLE
Add dependency and first program test

### ISSUE THREAD

**Issue by Yoy017** [Yoy017/todo-manager#3]
Add the dependency PICOCLI into the pom.xml and write the first CLI program that prompt "Hello World!" when using $ hello

**Comment by CamilleThHEIG** [comment]
Instead of "$ hello", I would suggest "$ todoManager"

**Comment by Yoy017** [comment]
The picocli has been added to the pom.xml. We now need to create the first hello world program for a good start so we can take inspiration on it later.
